# Generated by Django 5.2.4 on 2025-08-03 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('poster_path', models.CharField(blank=True, max_length=200)),
                ('release_date', models.CharField(blank=True, max_length=20)),
                ('overview', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('want_to_watch', 'Want to Watch'), ('watching', 'Watching'), ('watched', 'Watched')], default='want_to_watch', max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('watched_date', models.DateTimeField(blank=True, null=True)),
                ('available_providers', models.JSONField(blank=True, default=dict)),
                ('last_provider_check', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_date'],
                'unique_together': {('user', 'tmdb_id', 'media_type')},
            },
        ),
    ]
